version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      DATABASE_HOST: mysql
      DATABASE_NAME: pet-demo
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
    depends_on:
      - mysql
  mysql:
    image: mysql:5
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "root"
